POST http://localhost:3000/user/signin
Content-Type: application/json

{
  "name": "admin",
  "password": "123456"
}

###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name": "admin1",
  "password": "123456"
}

###
DELETE http://localhost:3000/user/signout

###
GET http://localhost:3000/conversations/{user_id}/all
Content-Type: application/json
Authorization: Bear eyJuYW1lIjoiYWRtaW4iLCJpZCI6MX0=

###
GET http://localhost:3000/conversation/{coversation_id}/detail
Content-Type: application/json
Authorization: Bear eyJuYW1lIjoiYWRtaW4iLCJpZCI6MX0=
